#!yaml
options:
  max-time: 10 # configure default 10 minute timeout (https://jira.atlassian.com/browse/BCLOUD-13491)
  
image:
  name: node:16.10.0-alpine3.14

prepareNodeModules: &prepareNodeModules
  step:
    name: install
    script:
      - export APP_ENV="production"
      - npm install --no-fund --no-audit --no-progress
    artifacts:
      - node_modules/**

qa: &qa
  parallel:
      - step:
          name: lint
          script:
            - export APP_ENV="production"
            - cp ./config.json.dist ./config.json
            - npm run lint

      - step:
          name: build
          script:
            - export APP_ENV="production"
            - cp ./config.json.dist ./config.json
            - npm run build

      - step:
          name: unit-test
          script:
            - npm run test

pipelines:
  branches:
    'master': # executed on branch "master", each time that code is updated
      - <<: *prepareNodeModules
      - <<: *qa

    'develop': # executed on branch "develop", each time that code is updated
      - <<: *prepareNodeModules
      - <<: *qa

  pull-requests:
    '**': # executed on each branch that has an open PR, each time that code is updated
      - <<: *prepareNodeModules
      - <<: *qa

  tags:
    '*': # executed on tag
      - <<: *prepareNodeModules
      - <<: *qa
